# Generated by Django 3.2.13 on 2022-05-04 16:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo_api', '0002_alter_webuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование проекта')),
                ('git_url', models.URLField(max_length=512, verbose_name='Ссылка на страницу GitHub')),
                ('authors', models.ManyToManyField(to='todo_api.WebUser', verbose_name='Авторы проекта')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1024, verbose_name='Текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_user', to='todo_api.webuser', verbose_name='Автор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_project', to='todo_work.project', verbose_name='Проект')),
            ],
        ),
    ]
