# Generated by Django 3.2.13 on 2022-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_alter_webuser_options'),
        ('todo_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(related_name='authors_project', to='todo_api.WebUser', verbose_name='Авторы проекта'),
        ),
    ]
